services:
  db:
    platform: linux/x86_64
    image: mysql:8.0.27
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
    volumes: 
      - mysql-data:/var/lib/mysql
    ports:
      - 3336:3306
    networks:
      vpcbr:
        ipv4_address: 10.0.0.12
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: gs-docker-php56:latest
    ports:
      - 8000:80
    volumes:
      - type: bind
        source: /var/www/html
        target: /var/www/html    
    networks:
      vpcbr:
        ipv4_address: 10.0.0.17       
    depends_on:
      - db
volumes:
  mysql-data:
networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.0.0/16
         gateway: 10.0.0.1