services:
  db:
    build:
      context: ./bd
      dockerfile: Dockerfile
    platform: linux/x86_64
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_USER: web
      MYSQL_PASSWORD: web
    volumes: 
      - mysql-data:/var/lib/mysql
    ports:
      - 8306:3306
    networks:
      vpcbr:
        ipv4_address: 10.0.0.12
  php56:
    build:
      context: ./php56
      dockerfile: Dockerfile
    image: php56:latest
    ports:
      - 8080:80
    volumes:
      - type: bind
        source: /var/www/html
        target: /var/www/html    
    networks:
      vpcbr:
        ipv4_address: 10.0.0.17       
    depends_on:
      - db
  php82:
    build:
      context: ./php82
      dockerfile: Dockerfile
    image: php82:latest
    ports:
      - 8082:80
    volumes:
      - type: bind
        source: /var/www/html
        target: /var/www/html    
    networks:
      vpcbr:
        ipv4_address: 10.0.0.18       
    depends_on:
      - db
volumes:
  mysql-data:
networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.0.0/16
         gateway: 10.0.0.1